apiVersion: v1 
kind: Service 
metadata:
  name: redis-voting-service
  labels: 
    name: redis-voting-service
    app: demo-voting-app
spec: 
  ports:
    - port: 6379
      targetPort: 6379
  selector: 
     name: redis-voting-pod
     app: demo-voting-app

  # Since it is an internal service, we will not be using the NodePort. NodePort is used for services which needs
  # to be accessed from outside the POD i.e. in our case it is Voting App and Result App.  